#!/usr/bin/env python3
"""
scripts/render-config.py — Canonical YAML → Hermes Generated Config

Reads canonical sources (provider_registry, model_aliases, mcp_registry)
and produces Hermes-compatible config.generated.yaml and mcp.generated.yaml.

SECURITY:
  - API key values are NEVER written to generated files.
    Generated config references the env var NAME only; Hermes resolves from env.
  - Senpi MCP is hard-excluded from the analysis profile at renderer level,
    regardless of mcp_registry.yaml profile settings.
  - Warnings are printed to stderr; no secret values are logged.

Usage:
  python3 scripts/render-config.py --profile analysis --data-dir /data
  python3 scripts/render-config.py --profile execution --data-dir /data
  python3 scripts/render-config.py --profile analysis --dry-run
  python3 scripts/render-config.py --validate-only --data-dir /data
"""

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# ---------------------------------------------------------------------------
# Security: MCP servers that are NEVER allowed in the analysis profile,
# regardless of what mcp_registry.yaml says.
# ---------------------------------------------------------------------------
SENPI_MCP_NAMES = frozenset({"senpi", "senpi-mcp", "senpi_mcp", "senpi-trading"})
ANALYSIS_PROFILE_DENIED_MCP = SENPI_MCP_NAMES  # extend if needed

GENERATED_FILE_HEADER = """\
# =============================================================================
# AUTO-GENERATED — DO NOT EDIT
# Generated by: scripts/render-config.py
# Profile     : {profile}
# Generated   : {timestamp}
#
# To change this file, edit the canonical YAML sources in /data/providers/,
# /data/mcp/, or /data/risk/, then restart the container.
# =============================================================================

"""


# ---------------------------------------------------------------------------
# Logging helpers — never log secret values
# ---------------------------------------------------------------------------

def log(msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] [CONF ] {msg}")


def warn(msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] [CONF ] WARN: {msg}", file=sys.stderr)


def err(msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] [CONF ] ERROR: {msg}", file=sys.stderr)


def load_yaml(path: Path) -> dict:
    """Load a YAML file; return empty dict if missing (with warning)."""
    if not path.exists():
        warn(f"Canonical file not found, skipping: {path}")
        return {}
    try:
        with open(path) as f:
            result = yaml.safe_load(f) or {}
        if not isinstance(result, dict):
            warn(f"Expected YAML dict in {path}, got {type(result).__name__} — skipping")
            return {}
        return result
    except yaml.YAMLError as e:
        err(f"YAML parse error in {path}: {e}")
        sys.exit(1)


def resolve_env_name(value: str) -> str:
    """Extract env var name from '${VAR_NAME}' format without resolving its value."""
    if isinstance(value, str) and value.startswith("${") and value.endswith("}"):
        return value[2:-1]
    return ""


def resolve_env_value(value: str) -> str:
    """Resolve '${VAR_NAME}' env references to their values (for non-secret fields only)."""
    if not isinstance(value, str):
        return value
    env_name = resolve_env_name(value)
    if env_name:
        resolved = os.environ.get(env_name, "")
        if not resolved:
            warn(f"Env var not set or empty: {env_name}")
        return resolved
    return value


def resolve_env_in_dict(d: dict) -> dict:
    """Recursively resolve ${VAR} references in a dict (for non-secret fields)."""
    result = {}
    for k, v in d.items():
        if isinstance(v, dict):
            result[k] = resolve_env_in_dict(v)
        elif isinstance(v, list):
            result[k] = v  # don't resolve inside lists
        elif isinstance(v, str):
            result[k] = resolve_env_value(v)
        else:
            result[k] = v
    return result


# ---------------------------------------------------------------------------
# Provider resolution
# ---------------------------------------------------------------------------

def build_provider_map(registry: dict, aliases: dict) -> dict:
    """
    Resolve provider_registry + model_aliases into a per-alias config dict.

    SECURITY: api_key VALUES are never stored in the returned dict.
    Only the env var NAME (api_key_env) is kept; Hermes reads keys from env.
    """
    providers = registry.get("providers", {})
    alias_map = aliases.get("aliases", {})
    resolved = {}

    for alias_name, alias_cfg in alias_map.items():
        if not isinstance(alias_cfg, dict):
            continue

        provider_name = alias_cfg.get("provider")
        model = alias_cfg.get("model")

        if not provider_name or not model:
            warn(f"Alias '{alias_name}' missing provider or model — skipped")
            continue

        provider = providers.get(provider_name, {})
        if not provider:
            warn(f"Provider '{provider_name}' not found for alias '{alias_name}' — skipped")
            continue

        if not provider.get("enabled", True):
            log(f"  ~ Disabled provider '{provider_name}' for alias '{alias_name}' — skipped")
            continue

        # Resolve api_key_env name (NOT the value)
        api_key_env = provider.get("api_key_env", "")
        if not api_key_env:
            warn(f"Provider '{provider_name}' has no api_key_env — alias '{alias_name}' skipped")
            continue

        # Check if the env var actually has a value (for early warning)
        if not os.environ.get(api_key_env):
            warn(f"Env var '{api_key_env}' is not set — alias '{alias_name}' will fail at runtime")

        # Resolve base_url (not a secret — can be written to config)
        base_url = provider.get("base_url", "")
        if not base_url:
            base_url_env_name = provider.get("base_url_env", "")
            if base_url_env_name:
                base_url = os.environ.get(base_url_env_name, "")

        resolved[alias_name] = {
            "provider":    provider_name,
            "model":       model,
            "base_url":    base_url,
            "api_key_env": api_key_env,   # env var NAME only — no value
            "max_tokens":  alias_cfg.get("max_tokens", 4096),
            "temperature": alias_cfg.get("temperature", 0.3),
        }
        log(f"  ✓ Alias resolved: {alias_name} → {provider_name}/{model} (key=${{{api_key_env}}})")

    return resolved


# ---------------------------------------------------------------------------
# MCP config — with hardened profile filtering
# ---------------------------------------------------------------------------

def build_mcp_config(registry: dict, profile: str) -> dict:
    """
    Filter mcp_registry.yaml to only include servers valid for the given profile.

    SECURITY: Senpi MCP is NEVER included in the analysis profile, even if
    mcp_registry.yaml lists it under profiles: [analysis, execution].
    This is enforced here at the renderer level, not just by config.
    """
    servers = registry.get("servers", {})
    result = {}

    for server_name, server_cfg in servers.items():
        if not isinstance(server_cfg, dict):
            continue

        if not server_cfg.get("enabled", True):
            log(f"  ~ MCP '{server_name}' disabled — skipped")
            continue

        # SECURITY: Hard-block Senpi MCP in analysis profile
        server_name_lower = server_name.lower()
        if profile == "analysis" and server_name_lower in ANALYSIS_PROFILE_DENIED_MCP:
            log(f"  ✗ MCP '{server_name}' BLOCKED in analysis profile "
                "(Senpi trading MCP never loads in analysis)")
            continue

        profiles = server_cfg.get("profiles", ["analysis", "execution"])
        if profile not in profiles:
            log(f"  ~ MCP '{server_name}' not in profile '{profile}' — skipped")
            continue

        # Resolve env references in server env block (non-secret keys)
        env_raw = server_cfg.get("env", {}) or {}
        env_resolved = {}
        for k, v in env_raw.items():
            env_name = resolve_env_name(str(v)) if isinstance(v, str) else ""
            if env_name:
                # Store the env var NAME for Hermes to resolve, not the value
                # (Hermes MCP stdio protocol passes env to child processes)
                env_value = os.environ.get(env_name, "")
                if not env_value:
                    warn(f"MCP '{server_name}' env var '{env_name}' is not set")
                if env_value:  # only include env key if it actually has a value
                    env_resolved[k] = env_value
            elif v:
                env_resolved[k] = str(v)

        hermes_entry = {
            "transport": server_cfg.get("transport", "stdio"),
            "command":   server_cfg.get("command", ""),
            "args":      server_cfg.get("args", []),
        }
        if env_resolved:
            hermes_entry["env"] = env_resolved

        result[server_name] = hermes_entry
        risk_level = server_cfg.get("risk_level", "unknown")
        log(f"  ✓ MCP included: {server_name} [profile={profile}, risk={risk_level}]")

    return result


# ---------------------------------------------------------------------------
# Hermes config.generated.yaml
# ---------------------------------------------------------------------------

def render_hermes_config(
    profile: str,
    provider_map: dict,
    mcp_servers: dict,
    aliases_meta: dict,
    hermes_home: Path,
    workspace_dir: Path,
) -> dict:
    """
    Build the Hermes config dict.

    SECURITY: api_key is NOT written to the config file.
    The api_key_env field tells Hermes which env var to read.
    """
    # Determine default alias from profiles block in model_aliases
    profile_defaults = aliases_meta.get("profiles", {}).get(profile, {})
    default_alias = profile_defaults.get("default_alias") or (
        "analysis-deep" if profile == "analysis" else "trade-safe"
    )
    fallback_alias = profile_defaults.get("fallback_alias") or "general-fast"

    default_provider = provider_map.get(default_alias) or provider_map.get(fallback_alias)

    if not default_provider:
        err(f"No valid provider resolved for profile '{profile}'. "
            "Check provider_registry.yaml and model_aliases.yaml.")
        sys.exit(1)

    config: dict = {
        "model":       default_provider.get("model", ""),
        "provider":    default_provider.get("provider", ""),
        "base_url":    default_provider.get("base_url", ""),
        # SECURITY: api_key env var NAME only — Hermes reads from env
        "api_key":     f"${{{default_provider.get('api_key_env', '')}}}",
        "workspace":   str(workspace_dir),
    }

    if mcp_servers:
        config["mcp_servers"] = mcp_servers

    config["_meta"] = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "profile":      profile,
        "generator":    "render-config.py",
        "default_alias": default_alias,
        "hermes_home":  str(hermes_home),
        "canonical_sources": [
            "providers/provider_registry.yaml",
            "providers/model_aliases.yaml",
            "mcp/mcp_registry.yaml",
        ],
    }

    # Remove empty string values (keep False, 0, lists)
    config = {k: v for k, v in config.items() if v != "" and v is not None}

    return config


# ---------------------------------------------------------------------------
# MCP standalone generated yaml
# ---------------------------------------------------------------------------

def render_mcp_generated(profile: str, mcp_servers: dict) -> dict:
    return {
        "_meta": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "profile":      profile,
            "generator":    "render-config.py",
        },
        "mcp_servers": mcp_servers,
    }


# ---------------------------------------------------------------------------
# Write helper with header
# ---------------------------------------------------------------------------

def write_yaml_with_header(path: Path, data: dict, profile: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = GENERATED_FILE_HEADER.format(
        profile=profile,
        timestamp=datetime.now(timezone.utc).isoformat(),
    )
    with open(path, "w") as f:
        f.write(header)
        yaml.dump(data, f, allow_unicode=True, default_flow_style=False, sort_keys=False)
    log(f"  ✓ Written: {path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Hermes-Senpi Config Renderer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Render analysis config
  python3 scripts/render-config.py --profile analysis --data-dir /data

  # Dry-run (stdout only, no files written)
  python3 scripts/render-config.py --profile analysis --dry-run

  # Validate canonical YAML files without rendering
  python3 scripts/render-config.py --validate-only --data-dir /data
""",
    )
    parser.add_argument("--profile",       default="analysis",
                        choices=["analysis", "execution"])
    parser.add_argument("--data-dir",     default="/data")
    parser.add_argument("--hermes-home",  default=None)
    parser.add_argument("--output-hermes", default=None)
    parser.add_argument("--output-mcp",   default=None)
    parser.add_argument("--dry-run",      action="store_true",
                        help="Print generated config to stdout, do not write files")
    parser.add_argument("--validate-only", action="store_true",
                        help="Validate canonical files and exit without generating")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    profile  = args.profile

    hermes_home   = Path(args.hermes_home) if args.hermes_home else \
                    data_dir / ".hermes" / profile
    output_hermes = Path(args.output_hermes) if args.output_hermes else \
                    hermes_home / "config.generated.yaml"
    output_mcp    = Path(args.output_mcp) if args.output_mcp else \
                    data_dir / "mcp" / "mcp.generated.yaml"
    workspace_dir = data_dir / "workspace"

    log(f"Config renderer starting (profile={profile})")
    log(f"  data_dir    : {data_dir}")
    log(f"  hermes_home : {hermes_home}")
    if not args.dry_run and not args.validate_only:
        log(f"  output      : {output_hermes}")
        log(f"  mcp output  : {output_mcp}")

    # --- Load canonical files ---
    log("Loading canonical config files...")
    provider_registry = load_yaml(data_dir / "providers" / "provider_registry.yaml")
    model_aliases     = load_yaml(data_dir / "providers" / "model_aliases.yaml")
    mcp_registry      = load_yaml(data_dir / "mcp" / "mcp_registry.yaml")

    # --- Resolve providers ---
    log("Resolving provider aliases...")
    provider_map = build_provider_map(provider_registry, model_aliases)

    if not provider_map:
        err("No valid provider aliases resolved. "
            "Check provider_registry.yaml (enabled providers) and model_aliases.yaml, "
            "and verify that required env vars are set in Railway Variables.")
        sys.exit(1)

    if args.validate_only:
        log(f"Validation passed — {len(provider_map)} alias(es) resolved")
        log(f"MCP registry has {len(mcp_registry.get('servers', {}))} server(s)")
        log("--validate-only: no files written")
        return

    # --- Filter MCP servers ---
    log(f"Filtering MCP servers for profile '{profile}'...")
    mcp_servers = build_mcp_config(mcp_registry, profile)

    if not mcp_servers:
        warn(f"No active MCP servers for profile '{profile}'")

    # --- Render configs ---
    log("Rendering config.generated.yaml...")
    hermes_config = render_hermes_config(
        profile=profile,
        provider_map=provider_map,
        mcp_servers=mcp_servers,
        aliases_meta=model_aliases,
        hermes_home=hermes_home,
        workspace_dir=workspace_dir,
    )
    mcp_config = render_mcp_generated(profile, mcp_servers)

    # --- Output ---
    if args.dry_run:
        log("--- DRY RUN: config.generated.yaml ---")
        print(yaml.dump(hermes_config, allow_unicode=True, default_flow_style=False, sort_keys=False))
        log("--- DRY RUN: mcp.generated.yaml ---")
        print(yaml.dump(mcp_config, allow_unicode=True, default_flow_style=False, sort_keys=False))
    else:
        write_yaml_with_header(output_hermes, hermes_config, profile)
        write_yaml_with_header(output_mcp, mcp_config, profile)

    log("Config renderer completed ✓")


if __name__ == "__main__":
    main()
